"""add tender information fields

Revision ID: 302b2ffb2d1e
Revises: f33cec1c93fb
Create Date: 2026-08-08 22:17:32.102413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302b2ffb2d1e'
down_revision: Union[str, Sequence[str], None] = 'f33cec1c93fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('nit_number', sa.String(length=255), nullable=True))
    op.add_column('tenders', sa.Column('tender_date', sa.String(length=50), nullable=True))
    op.add_column('tenders', sa.Column('project_location', sa.String(length=255), nullable=True))
    op.add_column('tenders', sa.Column('project_length_km', sa.Float(), nullable=True))
    op.add_column('tenders', sa.Column('project_cost_cr', sa.Float(), nullable=True))
    op.add_column('tenders', sa.Column('bid_start_date', sa.String(length=50), nullable=True))
    op.add_column('tenders', sa.Column('bid_end_date', sa.String(length=50), nullable=True))
    op.add_column('tenders', sa.Column('bid_opening_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'bid_opening_date')
    op.drop_column('tenders', 'bid_end_date')
    op.drop_column('tenders', 'bid_start_date')
    op.drop_column('tenders', 'project_cost_cr')
    op.drop_column('tenders', 'project_length_km')
    op.drop_column('tenders', 'project_location')
    op.drop_column('tenders', 'tender_date')
    op.drop_column('tenders', 'nit_number')
    # ### end Alembic commands ###
